version: "3"
services:
  web:
    build: .
    container_name: linka
    image: linka_app:1.0.0
    command: bash -c 'python3 /linka/manage.py runserver --noreload 0.0.0.0:80'
    ports:
      - 80:80
    volumes:
      - ./linka:/linka
    depends_on:
      - sqlserver
      - neo4j
    environment:
      NEO4J_BOLT_URL: "bolt://neo4j:test1234@neo4j:7687/linka"
      SQLSERVER_DB: "linka_db"
      SQLSERVER_USER: "sa"
      SQLSERVER_PASSWORD: "YourPassword123!"
      SQLSERVER_HOST: "sqlserver"
      SQLSERVER_PORT: "1433"
    networks:
      - linka_net

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourPassword123!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    networks:
      - linka_net
    volumes:
      - ./mssql_data:/var/opt/mssql

  neo4j:
    image: neo4j:5.21-enterprise
    ports:
      - "7474:7474"   # Neo4j browser (HTTP UI)
      - "7687:7687"   # Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/test1234
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=eval
    networks:
      - linka_net
    # volumes:
    #   - neo4j_data:/data

networks:
  linka_net:

  # hostnet:
  #   external: true
  #   name: host