services:
  neo4j:
    image: neo4j:5.23-community
    container_name: linka_neo4j
    restart: unless-stopped
    ports:
      - "7474:7474" # HTTP UI
      - "7687:7687" # Bolt
    environment:
      - NEO4J_AUTH=neo4j/neo4j_password
      - NEO4J_dbms_security_auth__minimum__password__length=8
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=1g
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      
volumes:
  neo4j_data:
  neo4j_logs:
