# Generated by Django 5.2.6 on 2025-09-11 07:07

import django.db.models.deletion
import linka.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linka', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=128, null=True)),
                ('last_name', models.CharField(blank=True, max_length=128, null=True)),
                ('hebrew_first_name', models.CharField(blank=True, max_length=128, null=True)),
                ('hebrew_last_name', models.CharField(blank=True, max_length=128, null=True)),
                ('gender', models.CharField(blank=True, choices=[('m', 'male'), ('f', 'female'), ('o', 'Other')], max_length=10, null=True)),
                ('education', models.CharField(blank=True, choices=[('none', 'No Formal Education'), ('primary', 'Primary School'), ('secondary', 'Secondary School'), ('high_school', 'High School'), ('diploma', 'Diploma'), ('bachelor', 'Bachelor’s Degree'), ('master', 'Master’s Degree'), ('doctorate', 'Doctorate / PhD'), ('other', 'Other')], max_length=20, null=True)),
                ('institution', models.CharField(blank=True, max_length=128, null=True)),
                ('adddress', models.CharField(blank=True, max_length=128, null=True)),
                ('martial_status', models.CharField(blank=True, max_length=128, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, null=True)),
                ('father_name', models.CharField(blank=True, max_length=128, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=128, null=True)),
                ('job', models.CharField(blank=True, max_length=128, null=True)),
                ('military_job', models.CharField(blank=True, max_length=128, null=True)),
                ('unit', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True)),
                ('country_code', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='role',
            name='role_person',
        ),
        migrations.CreateModel(
            name='AcountIdModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('signal', 'Signal'), ('slack', 'Slack'), ('other', 'Other')], max_length=64)),
                ('account_id', models.CharField(max_length=128)),
            ],
            options={
                'unique_together': {('platform', 'account_id')},
            },
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(unique=True, upload_to=linka.models.update_image_path)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='linka.personmodel')),
            ],
        ),
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(unique=True, upload_to=linka.models.update_file_path)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='linka.personmodel')),
            ],
        ),
        migrations.CreateModel(
            name='EmailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='linka.personmodel')),
            ],
        ),
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('poeple', models.ManyToManyField(to='linka.personmodel')),
            ],
        ),
        migrations.AddField(
            model_name='personmodel',
            name='phone_numbers',
            field=models.ManyToManyField(to='linka.phonenumbermodel'),
        ),
        migrations.CreateModel(
            name='RoleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=128, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='linka.rolemodel')),
                ('role_person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='linka.personmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AlterUniqueTogether(
            name='personmodel',
            unique_together={('first_name', 'last_name')},
        ),
    ]
